# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 18:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='added_at',
        ),
    ]
