# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 18:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_remove_question_added_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='added_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2016, 3, 5, 18, 33, 8, 227593, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
